# syntax=docker/dockerfile:1.4
FROM ghcr.io/foundry-rs/foundry as base

ENV ANVIL_IP_ADDR="0.0.0.0"
WORKDIR /anvil

USER root
RUN apt install -y screen
COPY scripts/foundry.sh .
RUN chmod +x ./foundry.sh
USER foundry

# Expose local chain ports.
EXPOSE 9601 9602 9603 9604 9605 9606 9607 9608 9609

CMD ["./foundry.sh"]
