databases:
  - name: clicker-postgres
    databaseName: clicker_db
    user: clicker_user
    plan: free
    region: oregon

services:
  # Redis Instance
  - type: redis
    name: clicker-redis
    plan: free
    region: oregon
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  # Express Backend API
  - type: web
    name: clicker-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    envVars:
      - key: BACKEND_PORT
        value: 4000
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: clicker-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: clicker-redis
          type: redis
          property: connectionString
    healthCheckPath: /health

  # Telegram Bot (runs as web service with long polling)
  - type: worker
    name: clicker-bot
    runtime: docker
    dockerfilePath: ./bot/Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: clicker-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: clicker-redis
          type: redis
          property: connectionString
      - key: QUEUE_REDIS_URL
        fromService:
          name: clicker-redis
          type: redis
          property: connectionString
      - key: ENABLE_WEBHOOKS
        value: false
      - key: DATA_ENCRYPTION_KEY
        sync: false
      - key: REFERRAL_CRYPTO_KEY
        sync: false
      - key: REFERRAL_CRYPTO_IV
        sync: false
      - key: NODE_ENV
        value: production

  # React Web App (Static Site)
  - type: web
    name: clicker-webapp
    runtime: static
    buildCommand: bun install && bun run build
    staticPublishPath: ./dist
    rootDir: ./web
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: clicker-backend
          type: web
          property: host

