name: Unit Tests and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      BOT_TOKEN: test-token
      REDIS_URL: redis://localhost:6379
      QUEUE_REDIS_URL: redis://localhost:6379
      PG_HOST: localhost
      PG_PORT: 5432
      PG_USER: test
      PG_PASSWORD: test
      PG_DATABASE: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.19

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run unit tests with coverage
        run: |
          mkdir -p coverage
          bun test --coverage --coverage-reporter=lcov --coverage-dir=coverage src/tests/unit/**/*.test.ts

      - name: Verify coverage files
        run: |
          echo "Coverage directory contents:"
          ls -la coverage/
          echo "Looking for lcov.info file:"
          find coverage/ -name "*.info" -o -name "lcov*" || echo "No lcov files found"
          echo "Coverage file size:"
          wc -l coverage/lcov.info || echo "lcov.info not found"

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
